---
- name: assert that EULA is accepted
  assert:
    that: minecraft_server_accept_eula

- name: make sure that directory is created
  file:
    path: "{{ minecraft_compose_directory }}"
    state: directory
    mode: 0770

- name: temnplate docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ minecraft_compose_directory }}/docker-compose.yml"
  notify: docker compose up

- name: enforce docker compose up if required
  shell: "cd {{ minecraft_compose_directory }} && docker-compose up -d"
  when: minecraft_enforce_compose_up